---
AWSTemplateFormatVersion: "2010-09-09"

Description: "This template creates TES frontend infrastructure"

Parameters:
  Stage:
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "prod"

Resources:
  StaticFilesHostBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Stage}-tes-static-files-host-s3-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
  StaticFilesHostBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticFilesHostBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource:
              Fn::Join:
                - ''
                - - "arn:aws:s3:::"
                  - !Ref StaticFilesHostBucket
                  - '/*'